repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
        files: 'commetts/*'
    -   id: end-of-file-fixer
        files: 'commetts/*'
    -   id: check-docstring-first
        files: 'commetts/*'
    -   id: check-json
        files: 'commetts/*'
    -   id: check-added-large-files
        files: 'commetts/*'
    -   id: check-yaml
        files: 'scripts/*'
    -   id: requirements-txt-fixer
    -   id: flake8
        files: 'commetts/*'
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
        files: 'commetts/*'
-   repo: https://github.com/pre-commit/pre-commit
    rev: v1.13.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
    -   id: reorder-python-imports
        files: 'commetts/*'
        language_version: python3.6
